# Generated by Django 3.2.4 on 2023-07-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datasets',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('position', models.CharField(default='', max_length=250, verbose_name='position')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='experiments_types',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('pathname', models.CharField(max_length=10, verbose_name='pathname')),
                ('path_type', models.CharField(max_length=10, verbose_name='path_type')),
                ('path', models.CharField(max_length=10, verbose_name='path')),
                ('parent_id', models.CharField(max_length=50, verbose_name='parent_id')),
                ('dataset_id', models.CharField(max_length=50, verbose_name='dataset_id')),
            ],
            options={
                'db_table': 'experiments_types',
            },
        ),
        migrations.CreateModel(
            name='network_and_experiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('network_id', models.CharField(max_length=50, verbose_name='network_id')),
            ],
            options={
                'db_table': 'network_and_experiment',
            },
        ),
        migrations.CreateModel(
            name='networks',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=250, verbose_name='filepath')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='pic_and_experiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('pic_id', models.CharField(max_length=50, verbose_name='pic_id')),
            ],
            options={
                'db_table': 'pic_and_experiment',
            },
        ),
        migrations.CreateModel(
            name='protein_and_pic',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('uniprot_id', models.CharField(max_length=50, verbose_name='uniprot_id')),
                ('pic_id', models.CharField(max_length=50, verbose_name='pic_id')),
            ],
            options={
                'db_table': 'protein_and_pic',
            },
        ),
        migrations.CreateModel(
            name='proteins',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('uniprot_id', models.CharField(max_length=64, verbose_name='uniprot_id')),
                ('protein_name', models.CharField(max_length=64, verbose_name='protein_name')),
                ('gene_symbol', models.CharField(max_length=64, verbose_name='gene_symbol')),
            ],
            options={
                'db_table': 'proteins',
            },
        ),
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=250, verbose_name='filepath')),
                ('doc_type', models.CharField(default='', max_length=5, verbose_name='doc_type')),
                ('label', models.CharField(default='', max_length=5, verbose_name='label')),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
    ]
