# Generated by Django 3.2.4 on 2023-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('dataset_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='dataset_id')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('position', models.CharField(default='', max_length=250, verbose_name='position')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='DocAndExperiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('doc_id', models.CharField(max_length=50, verbose_name='doc_id')),
            ],
            options={
                'db_table': 'doc_and_experiment',
            },
        ),
        migrations.CreateModel(
            name='ExperimentsTypes',
            fields=[
                ('experiment_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='experiment_id')),
                ('pathname', models.CharField(max_length=100, verbose_name='pathname')),
                ('path_type', models.CharField(max_length=10, verbose_name='path_type')),
                ('path', models.CharField(max_length=250, verbose_name='path')),
                ('parent_id', models.CharField(max_length=50, verbose_name='parent_id')),
                ('dataset_id', models.CharField(max_length=50, verbose_name='dataset_id')),
            ],
            options={
                'db_table': 'experiments_types',
            },
        ),
        migrations.CreateModel(
            name='NetworkAndExperiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('network_id', models.CharField(max_length=50, verbose_name='network_id')),
            ],
            options={
                'db_table': 'network_and_experiment',
            },
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('network_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='network_id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=250, verbose_name='filepath')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('protein_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='protein_id')),
                ('uniprot_accession_id', models.CharField(default='', max_length=50, verbose_name='uniprot_accession_id')),
                ('uniprotkb_id', models.CharField(default='', max_length=64, verbose_name='uniprotkb_id')),
                ('gene_name', models.CharField(default='', max_length=64, verbose_name='gene_name')),
            ],
            options={
                'db_table': 'proteins',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='doc_id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=250, verbose_name='filepath')),
                ('doc_type', models.CharField(default='', max_length=5, verbose_name='doc_type')),
                ('label', models.CharField(default='', max_length=5, verbose_name='label')),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
    ]
