# Generated by Django 4.2.1 on 2023-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='id')),
                ('uniprot_id', models.CharField(max_length=64, verbose_name='uniprot_id')),
                ('protein_name', models.CharField(max_length=64, verbose_name='protein_name')),
                ('gene_symbol', models.CharField(max_length=64, verbose_name='gene_symbol')),
            ],
            options={
                'db_table': 'Proteins',
            },
        ),
        migrations.DeleteModel(
            name='PacketInfo',
        ),
    ]
