# Generated by Django 3.2.4 on 2023-07-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments_types',
            name='path',
            field=models.CharField(max_length=250, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='experiments_types',
            name='pathname',
            field=models.CharField(max_length=100, verbose_name='pathname'),
        ),
    ]
