# Generated by Django 3.2.4 on 2023-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffResult',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='doc_id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=250, verbose_name='filepath')),
                ('network_id', models.CharField(max_length=50, verbose_name='network_id')),
            ],
            options={
                'db_table': 'diff_result',
            },
        ),
    ]
