# Generated by Django 3.2.4 on 2023-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_proteins_delete_packetinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='id')),
                ('filename', models.CharField(max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(max_length=150, verbose_name='filepath')),
                ('pic_type', models.CharField(max_length=5, verbose_name='pic_type')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
