# Generated by Django 3.2.4 on 2023-07-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230719_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_and_experiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('doc_id', models.CharField(max_length=50, verbose_name='doc_id')),
            ],
            options={
                'db_table': 'doc_and_experiment',
            },
        ),
        migrations.DeleteModel(
            name='pic_and_experiment',
        ),
        migrations.RenameField(
            model_name='experiments_types',
            old_name='id',
            new_name='experiment_id',
        ),
    ]
