# Generated by Django 3.2.4 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='filepath',
            field=models.CharField(max_length=250, verbose_name='filepath'),
        ),
    ]
