# Generated by Django 3.2.4 on 2023-07-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20230719_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networks',
            old_name='id',
            new_name='network_id',
        ),
    ]
