# Generated by Django 3.2.4 on 2023-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_experiments_network_and_experiment_networks_pic_and_experiment_protein_and_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
